CREATE OR REPLACE FORCE VIEW examoracle.vw_duracion_alquiler (codalq,nombre_inquilino,apellido_inquilino,n_vivienda,calle,poblacion,fecha_inicio,fecha_fin,dias_alquilados) AS
SELECT
    CODALQ,
    IQ.NOMINQ AS NOMBRE_INQUILINO,
    IQ.APEINQ AS APELLIDO_INQUILINO,
    VV.CODVIV AS N_VIVIENDA,
    VV.CALLVIV AS CALLE,
    VV.POBLVIV AS POBLACION,
    A.FINIALQ AS FECHA_INICIO,
    A.FFINALQ AS FECHA_FIN,
    TO_DATE(A.FFINALQ, 'DD-MM-YY') - TO_DATE(A.FINIALQ, 'DD-MM-YY') AS DIAS_ALQUILADOS
FROM 
    ALQUILER A
    INNER JOIN VIVIENDA VV
    ON VV.CODVIV = A.CODVIV
    INNER JOIN INQUILINO IQ
    ON IQ.CODINQ = A.CODINQ;